language: node_js
cache:
  directories:
    - node_modules
branches:
  only:
    - master
notifications:
  email: false
node_js:
  - '8'
before_script:
  - npm prune
script:
  - cp -r $TRAVIS_BUILD_DIR/src/* $TRAVIS_BUILD_DIR/
  - rm -rf $TRAVIS_BUILD_DIR/src
  - npx semantic-release
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
